DECLARE 
  CURSOR CUR_EMPLEADOS IS SELECT * FROM empleado_ventas;
  CURSOR CUR_SUC IS SELECT * FROM SUCURSAL;
  
BEGIN 
  FOR REC_EMP IN CUR_EMPLEADOS LOOP 
  FOR SUC IN CUR_SUC LOOP   
  IF REC_EMP.ID_CLIENTE=SUC.ID_CLIENTE THEN
  DBMS_OUTPUT.PUT_LINE('EMPLEADO:'||REC_EMP.NOMBRE_CLIENTE||' SUCURSAL:'||SUC.NOMBRE);
  END IF;
  END LOOP;
  END LOOP;
  END;
  
  /
  
  SELECT * FROM empleado_ventas;
  
  SET SERVEROUTPUT ON;
  
  SELECT EMPLEADO_VENTAS.ID_CLIENTE, EMPLEADO_VENTAS.NOMBRE_CLIENTE, SUCURSAL.NOMBRE FROM EMPLEADO_VENTAS JOIN SUCURSAL  ON EMPLEADO_VENTAS.ID_CLIENTE=SUCURSAL.ID_CLIENTE;
